; Torch Bearer scanner for LilyGo T-Display S3 (non-Pro)
[env:tdisplay-s3]
platform = espressif32@^6.9.0
board = lilygo-t-display-s3
framework = espidf
monitor_speed = 115200
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
