#!/usr/bin/env python3
"""Generates src/metrics_tables.h from the hCRI Companion app's spectralAnalysis.ts
(the CIE/CRI tables) and src/corr_table.h from a correction-curve JSON.
Usage: gen_tables.py <spectralAnalysis.ts> <corr.json>"""
import re, sys, json
ts = open(sys.argv[1]).read()

def arr(name):
    m = re.search(r'const %s = \[([^\]]*)\];' % name, ts)
    return [float(v) for v in m.group(1).split(',')]

def fmt(vals, per=10):
    out = []
    for i in range(0, len(vals), per):
        out.append('    ' + ','.join(repr(v) for v in vals[i:i+per]) + ',')
    return '\n'.join(out)

o = ['// GENERATED by tools/gen_tables.py from spectralAnalysis.ts -- do not edit.\n#pragma once\n']
for n in ('CMF_X', 'CMF_Y', 'CMF_Z'):
    v = arr(n); assert len(v) == 81
    o.append('static const float %s[81] = {\n%s\n};\n' % (n, fmt(v)))
o.append('static const float TCS_5NM[15][81] = {')
for i in range(1, 16):
    m = re.search(r'\n  %d: \[([^\]]*)\]' % i, ts)
    v = [float(x) for x in m.group(1).split(',')]; assert len(v) == 81
    o.append('  {\n%s\n  },' % fmt(v))
o.append('};\n')
m = re.search(r'const ROBERTSON[^=]*= \[(.*?)\n\];', ts, re.S)
rows = re.findall(r'\[([-\d.,]+)\]', m.group(1))
assert len(rows) == 31
o.append('static const float ROBERTSON[31][4] = {')
for r in rows: o.append('    {%s},' % r)
o.append('};\n')
for n in ('DAYLIGHT_S0', 'DAYLIGHT_S1', 'DAYLIGHT_S2'):
    v = arr(n); assert len(v) == 54
    o.append('static const float %s[54] = {\n%s\n};\n' % (n, fmt(v)))
open('src/metrics_tables.h', 'w').write('\n'.join(o))

d = json.load(open(sys.argv[2]))
nm, c = d['nm'], d['c']
assert nm[0] == 340 and nm[-1] == 1000 and len(c) == 661
c2 = ['// GENERATED by tools/gen_tables.py -- spectral correction for the Torch Bearer,\n'
      '// fitted against an HPCS-330P over 4 white lamps (multiply the raw spectrum by\n'
      '// CORR[nm - 340]). See README.\n#pragma once\n#define CORR_FIRST_NM 340\n#define CORR_N 661\n'
      'static const float CORR[CORR_N] = {\n' + fmt([round(v, 5) for v in c]) + '\n};\n']
open('src/corr_table.h', 'w').write(''.join(c2))
